from flask import Flask
from flask import request
from flask import jsonify

app = Flask(__name__)

# add config
app.config['FAKE_TOKEN'] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiMTEwNjEwODExNyIsIl9pZCI6IjYwY2FkMGQ3YzE1MzhlMTg2NjQ3OTIwZCIsInN0dWRlbnRfaWQiOiIxMTA2MTA4MTE3IiwiY3JlYXRlZF9hdCI6IjIwMjEtMDYtMTdUMDQ6MzQ6MzEuMDczWiIsInVwZGF0ZWRfYXQiOiIyMDIxLTA2LTE3VDA0OjM0OjMxLjA3M1oiLCJfX3YiOjAsInJlbWFyayI6ImFkbWluIiwiaWF0IjoxNjI2OTYzNzQ5LCJleHAiOjE2MjcwNTAxNDl9.tjoOVQWCJbRvB3CjknQ6_cHU0lr8bGaQF9D9Aok-Zl0"

# add router
from router import *